
branches:
  only:
  - master

dist: xenial
language: minimal

jobs:
  include:
    - stage: release
      script:
      - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
      - make build DEBUG=false
      - make tag_latest DEBUG=false
      - make release DEBUG=false
